# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Verify Ruby on Rails CI"
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: gestao-monitoramento-frota-db
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: admin

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1

      - name: Install PostgresSQL Client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle Install
        run: |
          gem install bundler
          bundle install

      - name: Setup Test Database
        env:
          SECRET_KEY_BASE: $RAILS_MASTER_KEY
          RAILS_ENV: actions
          DATABASE_URL: "postgres://rails:admin@localhost:5432/gestao-monitoramento-frota-db"
          PGHOST: localhost
          PGUSER: rails
        run: |
          echo "SECRET_KEY_BASE=$SECRET_KEY_BASE" >> .env.actions
          rails db:reset
          rails db:migrate
          rails db:prepare

      - name: Run All Tests
        run: |
          rails db:migrate RAILS_ENV=test
          rails test
          bundle exec cucumber
